/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************

 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int a = -4000;
int b = 200;
int result = 0;

int main(void)
{
    result = a+b;
    printf("Address of result: %p\n", &result);
	for(;;);
}
